ALTER TABLE ride_requests
  ADD COLUMN IF NOT EXISTS dest_lat DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS dest_lon DOUBLE PRECISION;

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS is_driver_notify BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS ntfy_topic VARCHAR(128);
